# Generated by Django 2.2.2 on 2020-01-16 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profiles')),
                ('phone', models.CharField(default='', max_length=14)),
                ('email', models.CharField(default='None', max_length=50)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isTeacher', models.BooleanField(default=False)),
                ('isStudent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
